[package]
name = "palette-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "^0.24"
itertools = "^0.10"
ordered-float = "^3.0"
palette = "^0.6"
quick-error = "^2.0"
rand = "^0.8"
rand_chacha = "^0.3"
serde_json = "^1.0"
